[tools]
android-sdk = "latest"
flutter = "stable"
java = "temurin-21"

[tasks.test]
description = "run the app"
run = "flutter test"

[tasks.linux]
description = "run the app on linux"
run = "flutter run -d linux"

[tasks.android]
description = "run the app on android"
run = "flutter run -d linux"

[tasks.clear-adb]
description = "run the app on android"
run = '''
adb kill-server
adb start-server
adb devices
'''
